# Generated by Django 3.0.8 on 2020-07-30 19:52

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_duartion', models.CharField(choices=[('2H', '2 hours'), ('4H', '4 hours')], max_length=150)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaners.Cleaner', validators=[books.models.validate_cleaner])),
            ],
        ),
    ]
